server:
  port: 9091 #服务提供方端口，自己定义

#指定当前服务的eureka注册地址
eureka:
  client:
    service-url:
      # 注册地址，9090端口是eureka-server的服务端口
      defaultZone: http://${eureka.instance.hostname}:9090/eureka
  instance:
    hostname: localhost

# 当前服务名称
spring:
  application:
    name: eureka-service